import { Payment } from "./types";

export const mockData: Payment[] = [
  {
    status: "fooey",
    amount: 3,
    email: "Marcellus_Schultz57@example.org",
    id: "1",
  },
  {
    status: "Sedan",
    amount: 33,
    email: "Nellie.Nienow@example.net",
    id: "2",
  },
  {
    status: "Osmium",
    amount: 7,
    email: "Robin88@example.net",
    id: "3",
  },
  {
    status: "pish",
    amount: 33,
    email: "Chandler_Douglas9@example.com",
    id: "4",
  },
  {
    status: "Regional",
    amount: 20,
    email: "Sarina_Bergstrom@example.com",
    id: "5",
  },
  {
    status: "fuchsia",
    amount: 19,
    email: "Manuel_OConner19@example.org",
    id: "6",
  },
  {
    status: "Meitnerium",
    amount: 23,
    email: "Keira57@example.com",
    id: "7",
  },
  {
    status: "Ergonomic",
    amount: 69,
    email: "Elwin1@example.org",
    id: "8",
  },
  {
    status: "pixel",
    amount: 43,
    email: "Jaylon10@example.net",
    id: "9",
  },
  {
    status: "Northwest",
    amount: 88,
    email: "Marielle_Hackett@example.org",
    id: "10",
  },
  {
    status: "West",
    amount: 64,
    email: "Nicklaus49@example.org",
    id: "11",
  },
  {
    status: "upshift",
    amount: 78,
    email: "Samantha22@example.net",
    id: "12",
  },
  {
    status: "World",
    amount: 49,
    email: "Hayley34@example.com",
    id: "13",
  },
  {
    status: "protocol",
    amount: 8,
    email: "Jaron_Mosciski@example.com",
    id: "14",
  },
  {
    status: "copying",
    amount: 82,
    email: "Curtis_Strosin7@example.net",
    id: "15",
  },
  {
    status: "Account",
    amount: 2,
    email: "Brock_Larson96@example.com",
    id: "16",
  },
  {
    status: "SCSI",
    amount: 61,
    email: "Dovie.Rice10@example.org",
    id: "17",
  },
  {
    status: "Africa",
    amount: 44,
    email: "Olen.DuBuque@example.net",
    id: "18",
  },
  {
    status: "Steel",
    amount: 2,
    email: "Miller_Simonis@example.net",
    id: "19",
  },
  {
    status: "maul",
    amount: 23,
    email: "Jarret.Lesch94@example.net",
    id: "20",
  },
  {
    status: "Analyst",
    amount: 93,
    email: "Sammie.Kiehn52@example.net",
    id: "21",
  },
  {
    status: "Bahamian",
    amount: 86,
    email: "Hardy.Green@example.com",
    id: "22",
  },
  {
    status: "technologies",
    amount: 67,
    email: "Gladys.Schmitt85@example.org",
    id: "23",
  },
  {
    status: "solutions",
    amount: 33,
    email: "Dewitt_Wuckert@example.com",
    id: "24",
  },
  {
    status: "transmit",
    amount: 97,
    email: "Norberto.Gutkowski18@example.org",
    id: "25",
  },
  {
    status: "azure",
    amount: 98,
    email: "Bo.Breitenberg68@example.net",
    id: "26",
  },
  {
    status: "or",
    amount: 29,
    email: "Beverly23@example.org",
    id: "27",
  },
  {
    status: "Handmade",
    amount: 65,
    email: "Willow_Wilderman@example.org",
    id: "28",
  },
  {
    status: "Legacy",
    amount: 42,
    email: "Loraine_Mayer90@example.net",
    id: "29",
  },
  {
    status: "male",
    amount: 82,
    email: "Maritza.Legros19@example.org",
    id: "30",
  },
  {
    status: "Burgs",
    amount: 47,
    email: "Rhea_Crooks47@example.org",
    id: "31",
  },
  {
    status: "Modern",
    amount: 32,
    email: "Darby24@example.org",
    id: "32",
  },
  {
    status: "invoice",
    amount: 2,
    email: "Lillian62@example.com",
    id: "33",
  },
  {
    status: "wireless",
    amount: 82,
    email: "Ethel.Hyatt@example.com",
    id: "34",
  },
  {
    status: "Nobelium",
    amount: 97,
    email: "Gust0@example.com",
    id: "35",
  },
  {
    status: "Kentucky",
    amount: 75,
    email: "Arielle70@example.org",
    id: "36",
  },
  {
    status: "Small",
    amount: 20,
    email: "Orrin23@example.net",
    id: "37",
  },
  {
    status: "agitated",
    amount: 35,
    email: "Rachel27@example.com",
    id: "38",
  },
  {
    status: "Northeast",
    amount: 34,
    email: "Keyon.Zulauf@example.net",
    id: "39",
  },
  {
    status: "Maine",
    amount: 74,
    email: "April.Breitenberg@example.com",
    id: "40",
  },
  {
    status: "Plastic",
    amount: 63,
    email: "Maudie.Borer12@example.net",
    id: "41",
  },
  {
    status: "chalk",
    amount: 97,
    email: "Rhea.Murazik86@example.com",
    id: "42",
  },
  {
    status: "becquerel",
    amount: 61,
    email: "Daisy.Kozey@example.com",
    id: "43",
  },
  {
    status: "compress",
    amount: 36,
    email: "Darlene35@example.net",
    id: "44",
  },
  {
    status: "wrong",
    amount: 63,
    email: "Breana.Heaney@example.org",
    id: "45",
  },
  {
    status: "Cambridgeshire",
    amount: 51,
    email: "Tressie.Schuster5@example.com",
    id: "46",
  },
  {
    status: "Account",
    amount: 22,
    email: "Birdie_Keebler@example.org",
    id: "47",
  },
  {
    status: "programming",
    amount: 46,
    email: "Susan_Fisher44@example.net",
    id: "48",
  },
  {
    status: "pascal",
    amount: 18,
    email: "Johnny_Hintz@example.com",
    id: "49",
  },
  {
    status: "Wooden",
    amount: 10,
    email: "Delfina.Doyle74@example.net",
    id: "50",
  },
];
